name: edgex-device-rest
base: core20
type: app
adopt-info: device-rest
license: Apache-2.0
title: EdgeX REST Device Service
summary: EdgeX device service for REST protocol
description: |
  This device service provides easy way for 3'rd party applications, 
  such as Point of Sale, CV Analytics, etc., to push data into EdgeX 
  via the REST protocol.

# delhi: 0, edinburgh: 1, fuji: 2, geneva: 3, ireland: 4
epoch: 4

# TODO: add armhf here when that's supported
architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-rest]

apps:
  device-rest:
    adapter: full
    command: bin/device-rest $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/startup-env-var.sh
    daemon: simple
    install-mode: disable
    environment:
      CONFIG_PRO_ARG: "--cp=consul://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-rest/res"
      REGISTRY_ARG: "--registry"
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-rest/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-rest/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-rest/secrets-token.json
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-rest

parts:

  hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps:
      - go/1.16/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"

  device-rest:
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    build-snaps:
      - go/1.16/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      GIT_VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      if [ -z "$GIT_VERSION" ]; then
        GIT_VERSION="0.0.0"
      fi
      snapcraftctl set-version ${GIT_VERSION}
      # this is needed for make build
      echo $GIT_VERSION > ./VERSION

      go mod tidy
      make build

      install -DT "./cmd/device-rest" "$SNAPCRAFT_PART_INSTALL/bin/device-rest"

      install -d "$SNAPCRAFT_PART_INSTALL/config/device-rest/res/"

      # copy all config files
      mkdir -p $SNAPCRAFT_PART_INSTALL/config/device-rest/res
      cp -rv cmd/res/configuration.toml $SNAPCRAFT_PART_INSTALL/config/device-rest/res/configuration.toml 
      cp -rv cmd/res/devices $SNAPCRAFT_PART_INSTALL/config/device-rest/res/devices     
      cp -rv cmd/res/profiles $SNAPCRAFT_PART_INSTALL/config/device-rest/res/profiles  

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rest/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rest/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

